// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfUP1jmW7kTK-Y8shU05r2ObJhEWMvSy4',
    appId: '1:953423061157:web:87188e766ea2c860f02d4c',
    messagingSenderId: '953423061157',
    projectId: 'flutter-firebase-app-6b37f',
    authDomain: 'flutter-firebase-app-6b37f.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-6b37f.appspot.com',
    measurementId: 'G-S80EKY9NY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYUuo8qsdbmvXdYkSa31vKh64OvpMt1o0',
    appId: '1:953423061157:android:c39d30565d12bc3bf02d4c',
    messagingSenderId: '953423061157',
    projectId: 'flutter-firebase-app-6b37f',
    storageBucket: 'flutter-firebase-app-6b37f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk1-rHGXsFThBw4gxVRLxVVx5lqxwP1eE',
    appId: '1:953423061157:ios:e33beac6e9956339f02d4c',
    messagingSenderId: '953423061157',
    projectId: 'flutter-firebase-app-6b37f',
    storageBucket: 'flutter-firebase-app-6b37f.appspot.com',
    iosClientId: '953423061157-70sd4vuj8jo6glksjflrt9ajst4mdjog.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk1-rHGXsFThBw4gxVRLxVVx5lqxwP1eE',
    appId: '1:953423061157:ios:e33beac6e9956339f02d4c',
    messagingSenderId: '953423061157',
    projectId: 'flutter-firebase-app-6b37f',
    storageBucket: 'flutter-firebase-app-6b37f.appspot.com',
    iosClientId: '953423061157-70sd4vuj8jo6glksjflrt9ajst4mdjog.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );
}
